keywords = [
    "else",
    "if",
    "while",
]

literals = [
    "integer",
]

punctuation = [
    ['{', "left curly bracket"],
    ['}', "right curly bracket"],
    ['(', "left parenthesis"],
    [')', "right parenthesis"],
    ['+', "plus sign"],
    ['-', "hyphen minus"],
    ['<', "less than sign"],
    [';', "semicolon"],
    ['=', "equals sign"],
]

tokens = [
    "error",
    "identifier",
    "whitespace",
]
