[package]
name = "conformance"
version = "0.1.0"
edition = "2018"

authors = ["cad97 <cad97@cad97.com>"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
syn = { version = "1.0.5", features = ["full"] }
proc-macro2 = "1.0.4"
