[package]
name = "tinyc_lexer"
version = "0.1.0"
edition = "2018"

authors = ["cad97 <cad97@cad97.com>"]

[dependencies]
serde = "1.0.101"
tinyc_grammar = { path = "../grammar" }

[dev-dependencies]
conformance = "0.2.0"
serde_yaml = "0.8.11"
